# Generated by Django 2.2.19 on 2022-08-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default=1, max_length=7, unique=True, verbose_name='Цвет в HEX'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True, verbose_name='Слаг id'),
            preserve_default=False,
        ),
    ]
