# Generated by Django 2.2.19 on 2022-08-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20220816_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='recipe_tags', through='recipes.RecipeTag', to='recipes.Tag', verbose_name='Тег'),
        ),
    ]
