# Generated by Django 2.2.19 on 2022-08-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_auto_20220816_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='recipe',
            field=models.ManyToManyField(through='recipes.RecipeFavorite', to='recipes.Recipe', verbose_name='Избранное'),
        ),
    ]
