# Generated by Django 2.2.19 on 2022-08-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_auto_20220817_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopingcart',
            name='recipe',
            field=models.ManyToManyField(through='recipes.RecipeShopingCart', to='recipes.Recipe', verbose_name='Избранное'),
        ),
    ]
