# Generated by Django 2.2.19 on 2022-08-22 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_auto_20220817_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeshopingcart',
            name='shoping_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.ShopingCart'),
        ),
    ]
