# Generated by Django 2.2.19 on 2022-08-23 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20220822_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopingcart',
            old_name='recipe',
            new_name='recipes',
        ),
        migrations.AlterField(
            model_name='recipeshopingcart',
            name='shoping_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ShopingCart'),
        ),
    ]
